#!/usr/bin/env bash
#
# Server-side, one-time: create the test database and /etc/salevali-crm/test.env
# if they do not exist yet. Piped over SSH by deploy-test.yml before the first
# deploy; a no-op on every run after that, so it costs one `test -f` forever.
#
# Assumes it runs as root on the Plesk box (the same access the Internship
# CRM's legacy SSH deploy used): `plesk db` provides admin MySQL access without
# any password handling, and /etc/salevali-crm is root-owned.
#
# Everything generated here stays ON THE SERVER: the DB password and the app
# secrets are created with openssl and written straight into the env file —
# they never pass through GitHub, the workflow log, or this repo.
#
set -euo pipefail

ENV_FILE="/etc/salevali-crm/test.env"
DB_NAME="salevali_crm_test"
DB_USER="salevali_test"

if [ -f "$ENV_FILE" ]; then
  echo "==> $ENV_FILE already exists — bootstrap is a no-op"
  exit 0
fi

command -v plesk >/dev/null || { echo "ERROR: plesk CLI not found — is this the right box/user?" >&2; exit 1; }

echo "==> Creating test database ${DB_NAME} and user ${DB_USER}"
DB_PASS=$(openssl rand -hex 16)
plesk db -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
# Two grants on purpose: localhost for anything run on the host, and 172.17.%
# for the app containers, which reach MySQL via the docker bridge gateway
# (host.docker.internal). The Internship CRM's preview DB user is grated the
# same way on this box, so the bind-address side is known to work.
plesk db -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
plesk db -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'172.17.%' IDENTIFIED BY '${DB_PASS}';"
plesk db -e "ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}'; ALTER USER '${DB_USER}'@'172.17.%' IDENTIFIED BY '${DB_PASS}';"
plesk db -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost'; GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'172.17.%'; FLUSH PRIVILEGES;"

echo "==> Writing $ENV_FILE"
mkdir -p /etc/salevali-crm
umask 077
cat > "$ENV_FILE" <<EOF
# SaleVali Marketing CRM — shared TEST environment secrets.
# Generated by infra/server/bootstrap-test-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Serves marketing.ersah.in and every marketing-pr<N>.ersah.in env.
# NEXTAUTH_URL is derived per-subdomain by the deploy — do not add it here.
DATABASE_URL='mysql://${DB_USER}:${DB_PASS}@127.0.0.1:3306/${DB_NAME}'
NEXTAUTH_SECRET='$(openssl rand -hex 32)'
HEALTH_TOKEN='$(openssl rand -hex 24)'
# Opts this database into the demo dataset (prisma/seed-demo.mjs), which also
# creates the fixed test sign-in admin@ersah.in. TEST ONLY — the future
# prod.env must never carry this flag.
ALLOW_DEMO_SEED='1'
EOF
chmod 600 "$ENV_FILE"

echo "==> Bootstrap complete"
